# Example: https://data-dive.com/multi-os-deployment-in-cloud-using-pyinstaller-and-github-actions

name: build

on: [push]

jobs:
  build:
    name: Build packages
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: linux
          - os: macos-latest
            target: macos
          - os: windows-latest
            target: windows
    env:
      # Run the script in test mode.
      TEST: 1
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install system dependencies
        run: ./bootstrap.sh ${{matrix.target}}
      - name: Build executable with pyinstaller
        run: ./build.sh ${{matrix.target}}
      - name: Check python script
        run: python3 src/joplin_sticky_notes.py
      - uses: actions/upload-artifact@v3
        with:
          name: joplin-sticky-notes
          path: ./dist/joplin-sticky-notes
      - name: Run the executable
        run: ./dist/joplin-sticky-notes
