# Example: https://data-dive.com/multi-os-deployment-in-cloud-using-pyinstaller-and-github-actions

name: build

on: [push]

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]
    env:
      # Run the executable in test and debug mode.
      TEST: 1
      QT_DEBUG_PLUGINS: 1 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install system dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt update
          sudo apt install libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-shape0 libxkbcommon-x11-0 --yes
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build executable with pyinstaller
        run: python -m PyInstaller joplin_sticky_notes.spec --noconfirm
      - uses: actions/upload-artifact@v3
        with:
          name: joplin-sticky-notes-${{ matrix.os }}
          path: ./dist/joplin-sticky-notes*
      - name: Run the executable
        run: ./dist/joplin-sticky-notes
