name: lint

on: [push]

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pip dependencies
        run: |
          pip install -r requirements.txt
          pip install black==22.6.0 flake8==5.0.4 mypy==0.971
          mypy --install-types
      - name: Run linting
        run: ./lint.sh
