name: test

on: [push]

jobs:
  build:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]
    env:
    #   # Run the script in test mode.
    #   TEST: 1
      # https://stackoverflow.com/a/55442821/7410886
      QT_QPA_PLATFORM: "offscreen"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install system dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt install libegl1-dev --yes
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run the tests
        run: python -m unittest
